// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgFormat.proto

package Exercise2;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Exercise3.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 fr = 1;</code>
   * @return Whether the fr field is set.
   */
  boolean hasFr();
  /**
   * <code>required int32 fr = 1;</code>
   * @return The fr.
   */
  int getFr();

  /**
   * <code>required int32 to = 2;</code>
   * @return Whether the to field is set.
   */
  boolean hasTo();
  /**
   * <code>required int32 to = 2;</code>
   * @return The to.
   */
  int getTo();

  /**
   * <code>required string msg = 3;</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>required string msg = 3;</code>
   * @return The msg.
   */
  String getMsg();
  /**
   * <code>required string msg = 3;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
