// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: handshakeMessageFormat.proto

package Exercise3;

public interface HandshakeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Exercise3.HandshakeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>required bool error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>required bool error = 2;</code>
   * @return The error.
   */
  boolean getError();
}
