// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgFormat.proto

package Exercise1;

public final class MsgFormat {
  private MsgFormat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Exercise3_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Exercise3_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017msgFormat.proto\022\tExercise3\".\n\007Message\022" +
      "\n\n\002fr\030\001 \002(\005\022\n\n\002to\030\002 \002(\005\022\013\n\003msg\030\003 \002(\tB\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Exercise3_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Exercise3_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Exercise3_Message_descriptor,
        new java.lang.String[] { "Fr", "To", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
